from pathlib import Path
import json,html,csv,shutil
root=Path(__file__).resolve().parent
out=root;(out/'assets').mkdir(parents=True,exist_ok=True);(out/'data').mkdir(exist_ok=True)
d=json.loads((root/'lotte_report/analysis_data.json').read_text(encoding='utf-8'))
movies=d['movies'];summary={'movies':movies,'sentiment':{k:sum(m['sentiment_counts'].get(k,0) for m in movies) for k in ['긍정 단서','부정 단서','혼합 단서','단서 없음']},'sample_total':len(d['reviews']),'display_total':sum(m['total_reviews'] for m in movies),'method':d['method']}
(out/'data/summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2),encoding='utf-8')
shutil.copyfile(root/'lotte_report/movies.csv',out/'data/movies.csv')
def e(x):return html.escape(str(x))
def heading(k,t,sub=''):return f'<div class="eyebrow reveal">{k}</div><h2 class="reveal">{t}</h2><p class="lead reveal">{sub}</p>'
def chart(id,klass=''):return f'<div id="{id}" class="chart reveal {klass}" aria-live="polite"></div>'
def note(t):return f'<p class="chart-note">{t}</p>'
def card(label,value,text):return f'<div class="metric reveal"><span>{label}</span><strong data-count="{value}">0</strong><p>{text}</p></div>'
slides=[]
def add(title,body,notes,klass=''):slides.append({'title':title,'body':body,'notes':notes,'klass':klass})
add('관람평을 읽으면, 경험이 보인다', '<div class="cover-copy"><div class="eyebrow reveal">CINEMA / AUDIENCE INTELLIGENCE</div><h1 class="reveal">관람평을 읽으면,<br><em>경험이 보인다.</em></h1><p class="cover-sub reveal">롯데시네마 예매순 TOP 10<br>공개 관람평 541개로 살펴본 영화와 극장 경험</p><div class="cover-meta reveal"><span>2026.10.02</span><span>FIRECRAWL × REVIEW ANALYSIS</span></div></div><div class="cover-stamp reveal">10 FILMS<br>541 VOICES</div>', '인기 기준은 현재 상영작 목록의 예매순입니다. 541개는 관객 수가 아니라 수집 리뷰 수입니다. 생성 이미지는 분석 결과를 보조하는 콘셉트 이미지입니다.','cover')
add('평가의 중심에는 서로 다른 기대가 있다',heading('01 / THE BIG PICTURE','평가의 중심에는<br><em>서로 다른 기대</em>가 있다.','배우의 연기, 이야기의 완성도, 그리고 극장에서의 경험.')+'<div class="metric-grid">'+card('분석 대상 영화',10,'예매순 상위 10편')+card('수집된 공개 관람평',541,'최신순 편의 표본')+card('전체 관람평 표시 합계',15345,'각 상세 페이지의 표시 수 합계')+'</div><div class="thesis reveal"><span>분석의 관점</span><p>영화의 강점과 관람 경험의 불만을<br>함께 읽어야 개선 지점이 보인다.</p></div>', '전체 표시 리뷰 합계 15,345개 중 541개를 수집했습니다. 감성 결과는 단어 표현의 단서이며 만족도 조사 결과가 아닙니다.')
add('인기는 예매순, 리뷰 규모는 또 다른 축',heading('02 / THE COHORT','인기는 예매순.<br><em>리뷰 규모는 또 다른 축.</em>','예매순 상위 10편 · 막대는 전체 관람평 표시 수')+chart('cohort')+note('순서는 롯데시네마 목록의 예매순입니다. 막대 길이는 예매율이나 수집 리뷰 수가 아닙니다.'),'오디세이의 전체 리뷰 표시 수가 가장 많지만 예매순은 5위입니다. 예매순과 누적 리뷰 규모는 서로 다른 정보입니다.')
add('동일한 60개도 대표하는 범위가 다르다',heading('03 / SAMPLE COVERAGE','같은 60개라도,<br><em>관찰한 범위는 다르다.</em>','수집 비중 = 수집 리뷰 / 해당 영화의 전체 관람평 표시 수')+chart('coverage')+note('100% 수집된 VR 콘서트도 n=16입니다. 표본 비중이 크다고 관객 전체를 대표하는 것은 아닙니다.'),'541개는 15,345개의 3.53%입니다. VR 콘서트는 표시된 16개를 모두 확보했지만 작은 표본입니다. 영화별 리뷰 작성 기간도 다릅니다.')
add('감성 표현의 분포',heading('04 / LANGUAGE SIGNALS','칭찬과 불만을 세되,<br><em>만족도로 읽지는 않는다.</em>','공개된 표현 사전으로 분류한 541개 리뷰의 언어 단서')+'<div class="split"><div>'+chart('sentiment')+'</div><div class="signal-copy reveal"><div class="bigline"><b>250</b><span>긍정 단서만 매칭</span></div><div class="bigline"><b>226</b><span>사전 표현 미매칭</span></div><p>‘단서 없음’은 중립이라는 뜻이 아닙니다.<br>짧은 리뷰, 은유, 맞춤법 변형을 놓칠 수 있습니다.</p><div class="pill">규칙 기반 분류 · 정확도 검증 없음</div></div></div>'+note('긍정 250 · 부정 42 · 혼합 23 · 단서 없음 226. 일부 부정 표현과 굿즈의 오매칭을 보정했습니다.'),'긍정 단서 46.2%를 만족률이라고 말하면 안 됩니다. 반어, 문맥, 장르 기대를 완전히 포착하는 모델이 아닙니다. 혼합은 긍정과 부정 표현이 함께 등장하는 리뷰입니다.')
add('영화마다 표현의 조합이 다르다',heading('05 / SIGNAL MIX','영화마다<br><em>표현의 조합이 다르다.</em>','100% 누적 막대 · 영화별 수집 표본 내 비중')+chart('sentimentMovies')+note('긍정·부정 표현의 매칭 비중입니다. 평점·만족도·영화의 우열을 비교하는 그래프가 아닙니다.'),'특히 VR 콘서트는 16개, 암살자(들)는 45개, 나머지 8편은 60개입니다. 분모 차이와 작성 시점 차이를 고려해야 합니다.')
add('서사와 배우가 가장 자주 포착됐다',heading('06 / RECURRING TOPICS','리뷰의 반복 주제는<br><em>서사와 배우.</em>','주제별 키워드가 매칭된 리뷰 수 · 한 리뷰는 여러 주제에 포함 가능')+chart('topics')+note('541개 표본 내 키워드 매칭입니다. 주제 합계는 중복을 포함하며 실제 모든 언급을 포착하지 못합니다.'),'정량 주제는 지정된 키워드의 매칭 수입니다. 굿즈와 포스터 품절 등 표현 사전에 없는 의견도 정성 읽기에서 발견했습니다.')
add('각 영화가 만드는 대화는 다르다',heading('07 / TOPIC MAP','각 영화가 만드는<br><em>대화는 다르다.</em>','셀에 마우스를 올리면 주제별 리뷰 수와 표본 내 비중을 확인할 수 있습니다.')+'<div class="chart-controls reveal"><button class="mode active" data-heat="rate">표본 내 비중</button><button class="mode" data-heat="count">리뷰 수</button><span>색이 진할수록 매칭 비중이 큽니다</span></div>'+chart('heatmap')+note('작품별 주제 키워드 빈도이며, 감정의 방향을 보여주는 표가 아닙니다. 복수 주제 매칭을 허용합니다.'),'비중 모드는 표본 규모 차이를 보정해 보기 위한 기술적 비율입니다. 만족도와는 무관합니다. 리뷰 수 모드도 함께 제공됩니다.')
add('연기와 서사, 두 개의 평가 축',heading('08 / TWO AXES','연기와 서사.<br><em>두 축을 함께 읽는다.</em>','X: 연기·배우 매칭 비중 / Y: 서사·연출 매칭 비중')+'<div class="split wide"><div>'+chart('scatter')+'</div><div class="side-insight reveal"><span class="rule-number">01</span><h3>가능한 사랑</h3><p>배우의 연기와 난해함·여운이 함께 논의된다.</p><span class="rule-number">02</span><h3>부활남: 더 레드</h3><p>배우의 코믹 연기와 개연성·CG에 대한 의견이 공존한다.</p><span class="rule-number">03</span><h3>인턴</h3><p>배우의 호흡, 원작과 달라진 캐릭터가 주요 해석 지점.</p></div></div>'+note('좌표는 주제 매칭 비중입니다. 연기력 점수·서사 완성도 점수·인과관계를 의미하지 않습니다.'),'표현 매칭을 두 축으로 나눈 탐색 그래프입니다. 가능한 사랑은 연기·배우 19개, 서사·연출 12개입니다. 부활남은 각각 17개와 11개입니다.')
add('무섭다는 말은 불만과 다르다',heading('09 / EXPECTATIONS','‘무섭다’는 말은<br><em>장르 기대에 따라 달라진다.</em>','공포·강도 주제가 포착된 리뷰를 비교했습니다.')+'<div class="dual-cards"><div class="story-card reveal"><span>01 / CUTE MEETS DARK</span><h3>극장판 치이카와</h3><div class="ratio"><b>15</b><small>/ 60개</small></div><p>귀여운 그림체와 어두운 이야기의 간극.<br>분위기에 대한 사전 기대가 반응을 가른다.</p><div class="mini-progress" style="--fill:25%"></div></div><div class="story-card reveal"><span>02 / HORROR AS A REWARD</span><h3>옵세션</h3><div class="ratio"><b>22</b><small>/ 60개</small></div><p>공포의 강도와 잔상이 장르적 재미로 언급.<br>자극·소음에 불편함을 느끼는 반응도 존재한다.</p><div class="mini-progress" style="--fill:36.667%"></div></div></div>'+note('공포·강도 키워드 매칭 수입니다. 무섭다는 표현을 부정 단어로 일괄 분류하지 않았습니다.'),'치이카와는 전체관람가라는 기대와 분위기의 간극이 중요합니다. 공식 등급을 바꾸어 해석하지 않습니다. 옵세션은 공포 장르 기대가 만족과 불편을 함께 만듭니다.')
add('작품의 강점과 불만은 공존한다',heading('10 / MIXED EXPERIENCE','작품의 강점과 불만은<br><em>같은 리뷰에 공존한다.</em>','부활남: 더 레드 · n=60')+'<div class="split"><div>'+chart('revival')+'</div><div class="quote-panel reveal"><div class="eyebrow">정성 해석 / 원문을 요약</div><h3>“배우와 속도감은 좋지만,<br>CG와 설정은 아쉽다.”</h3><p>코믹 연기와 빠른 흐름은 강점.<br>CG의 어색함과 개연성은 별도의 평가 축.</p><div class="pill">칭찬 한 줄로 불만을 덮지 않기</div></div></div>'+note('그래프는 주제별 매칭 수입니다. ‘영상·음향·기기’ 11개를 모두 CG 불만으로 해석할 수는 없습니다. 인용부는 여러 리뷰의 요약 문장입니다.'),'제시한 문장은 원문 직접 인용이 아니라 정성 해석을 압축한 문장입니다. 혼합 표현 7개가 있지만 혼합 표현 비율도 만족도는 아닙니다.')
add('VR에서는 운영이 콘텐츠가 된다',heading('11 / EXPERIENCE DESIGN','VR에서는<br><em>운영이 콘텐츠가 된다.</em>','엔하이픈 브이알콘서트 : 데스티니 · 수집 n=16')+'<div class="vr-layout"><div>'+chart('vr')+'<div class="vr-text reveal"><p><b>경험의 강점</b> 멤버를 가까이 보는 1인칭 경험</p><p><b>점검할 지점</b> 음량 · 초점 · 무게 · 착용 안내 · 응대</p></div></div><div class="asset-frame reveal"><img src="assets/vr.webp" alt="AI로 생성한 영화관 좌석 위 VR 기기 콘셉트 이미지"><span>AI CONCEPT VISUAL</span></div></div>'+note('지점 경험은 상반되며 별도 사실 확인이 필요합니다. 작은 표본으로 지점별 서비스의 우열을 판단할 수 없습니다.'),'영상·음향·기기 매칭 5개, 서비스·매너 3개입니다. 이는 각각 31.3%, 18.8%이며 복수 주제 포함 가능입니다. 특정 지점 전체를 부정적으로 규정하지 않습니다.')
add('큰 화면과 음향은 극장의 가치다',heading('12 / THE BIG-SCREEN VALUE','큰 화면과 음향.<br><em>다시 극장을 찾는 이유.</em>','극장 경험과 재관람에 관련된 주제 매칭 · 두 영화 모두 n=60')+chart('rewatch')+'<div class="takeaway reveal"><span>정성 해석</span><p>오디세이와 어벤져스 앙코르에서는<br>스케일·음향·향수·재관람 경험이 함께 언급됐다.</p></div>'+note('영상·음향·기기와 재관람·추천 의향의 매칭 수입니다. 실제 재관람률을 추정하지 않습니다.'),'오디세이는 두 주제가 각각 10개와 10개, 인피니티비전 어벤져스는 8개와 4개입니다. 포스터 품절 관련 의견도 정성 읽기에 반영합니다.')
briefs=[('귀여움 × 분위기','캐릭터의 매력과 어두운 이야기의 간극'),('몰입 × 해석 논쟁','긴장감·연기와 역사 해석에 대한 상반된 반응'),('배우 × CG','코믹 연기·속도감과 설정·CG의 아쉬움'),('오락성 × 원작 기대','배우·재미와 첫 작품 비교·포커 이해'),('스케일 × 재관람','큰 화면·음향과 긴 러닝타임'),('호흡 × 리메이크','배우들의 합과 캐릭터 변경에 대한 평가'),('연기 × 난해함','여운·몰입과 이해의 어려움'),('근접 경험 × 운영','VR의 몰입과 기기·음향·응대'),('공포 × 자극','장르적 재미와 소음·불편'),('향수 × 특별관','재관람 감동과 좌석·특전 경험')]
add('10편의 관람 포인트',heading('13 / FILM-BY-FILM','10편, <em>10개의 관람 포인트.</em>','정량 주제와 리뷰 본문의 정성 해석을 함께 읽었습니다.')+'<div class="film-grid">'+''.join(f'<div class="film-item reveal" style="--i:{i}"><span class="film-rank">{m["rank"]:02}</span><div><h3>{e(m["movie"])}</h3><b>{a}</b><p>{b}</p></div></div>' for i,(m,(a,b)) in enumerate(zip(movies,briefs)))+'</div>','모든 10편을 한 장에 요약했습니다. 이 표는 추천 순위가 아니며 예매순을 유지합니다. 각 내용은 표본의 정성 해석입니다.')
add('먼저 바꿀 것은 경험의 작은 마찰',heading('14 / ACTIONABLE INSIGHTS','먼저 바꿀 것은,<br><em>경험의 작은 마찰.</em>','리뷰에서 발견한 문제를 운영 점검과 관객 안내로 연결합니다.')+'<div class="action-layout"><div class="action-stack"><div class="action reveal"><b>01</b><div><h3>특전 안내를 구체적으로</h3><p>지점별 수량·소진 상태를 안내하고 기대와 현실의 간극을 줄이기</p></div></div><div class="action reveal"><b>02</b><div><h3>VR의 기본 경험을 안정적으로</h3><p>음량·초점·착용 지원·직원 응대를 현장에서 확인하기</p></div></div><div class="action reveal"><b>03</b><div><h3>관람 전 기대를 정확하게</h3><p>공포의 강도·러닝타임·특별관·원작과의 차이를 설명하기</p></div></div></div><div class="asset-frame reveal"><img src="assets/tickets.webp" alt="AI로 생성한 빈 티켓과 수집 카드의 콘셉트 이미지"><span>AI CONCEPT VISUAL</span></div></div>'+note('제안은 표본에서 도출한 점검 방향입니다. 효과 크기나 매출 증가를 검증한 결과는 아닙니다.'),'운영의 우선순위는 정량 점수 순위가 아닌 리뷰에서 발견한 점검 과제입니다. 모든 서비스 관련 주장은 현장 확인 후 조치해야 합니다.')
add('데이터가 말하는 범위를 지킨다',heading('15 / METHODOLOGY','데이터가 말하는<br><em>범위를 지킨다.</em>','결과를 신뢰하려면 수집과 분석의 경계를 함께 보여줘야 합니다.')+'<div class="method-grid"><div class="method reveal"><span>COLLECTION</span><h3>Firecrawl · 공개 페이지</h3><p>2026.10.02 KST 수집<br>예매순 TOP 10 · 최신순 리뷰<br>영화별 16~60개 확보</p></div><div class="method reveal"><span>CLASSIFICATION</span><h3>사전 매칭 · 복수 주제</h3><p>긍정 / 부정 / 혼합 / 단서 없음<br>원문과 매칭 표현으로 확인 가능<br>평점은 확보되지 않아 미제공</p></div><div class="method reveal"><span>LIMITATIONS</span><h3>편의 표본 · 시점 차이</h3><p>영화별 작성 기간이 다름<br>짧은 리뷰·다른 영화 중심 리뷰 포함<br>관람평은 전체 관객을 대표하지 않음</p></div><div class="method reveal"><span>NEXT STUDY</span><h3>기간과 표본을 맞추기</h3><p>동일 기간·최신순 + 공감순<br>실제 평점은 별도 수집<br>사전·분류 정확도 검증 필요</p></div></div>'+note('목록 최초 응답은 Firecrawl 캐시를 허용했습니다. 이미지 에셋은 생성형 AI 콘셉트이며 실제 영화 장면·시설 사진이 아닙니다.'),'의도한 모집단에 대한 무작위 표본이 아니므로 신뢰구간이나 유의성 검정을 제시하지 않습니다. 원문에 들어 있는 역사 주장과 일정은 사실 검증 자료가 아닙니다.')
add('좋은 영화 경험은 화면 밖에서도 완성된다','<div class="cover-copy"><div class="eyebrow reveal">THE TAKEAWAY</div><h1 class="reveal">좋은 영화 경험은<br><em>화면 밖에서도<br>완성된다.</em></h1><p class="cover-sub reveal">영화의 강점을 알리고,<br>관람 경험의 마찰을 줄이는 것.</p><div class="cover-meta reveal"><a href="data/movies.csv" download>영화 데이터 CSV ↗</a><a href="data/summary.json" download>분석 집계 JSON ↗</a></div></div>','덱의 결론은 표본의 정성 해석입니다. 작품의 강점을 전달하면서 운영에서 생기는 불편을 점검하자는 제안입니다.','cover closing')
add('출처와 분석 자료',heading('APPENDIX / SOURCES','출처와 <em>분석 자료.</em>','각 제목을 클릭하면 롯데시네마 상세 페이지로 이동합니다.')+'<div class="source-grid">'+''.join(f'<a class="source-link reveal" href="{m["source_url"]}" target="_blank" rel="noopener"><span>{m["rank"]:02}</span><b>{e(m["movie"])}</b><small>n={m["sample_reviews"]} · 전체 표시 {m["total_reviews"]:,} ↗</small></a>' for m in movies)+'</div><div class="source-footer reveal"><a href="https://www.lottecinema.co.kr/NLCHS/Movie/List?flag=1" target="_blank" rel="noopener">현재 상영작 · 예매순 ↗</a><a href="data/summary.json" download>집계와 표현 사전 JSON ↗</a><a href="assets/prompts.md">이미지 생성 프롬프트 ↗</a><p>Firecrawl 수집 · 2026.10.02 KST / 공개 리뷰의 규칙 기반 분석 및 정성 해석</p></div>','덱의 그래프는 집계 데이터를 사용합니다. 저장소에는 원본 수집·분석 자료도 보관했습니다. API 키와 .env는 포함하지 않습니다.')
sections=''
for i,s in enumerate(slides):
 sections+=f'<section class="slide {s["klass"]}" id="slide-{i+1}" aria-label="{i+1}. {e(s["title"])}" data-title="{e(s["title"])}" data-notes="{e(s["notes"])}"><div class="slide-inner">{s["body"]}</div><footer class="slide-footer"><span>CINEMA / REVIEW INTELLIGENCE</span><span>2026.10.02 · 최신순 편의 표본</span></footer></section>'
page=f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#100e10"><meta name="description" content="롯데시네마 예매순 상위 10편, 공개 관람평 541개 분석. 애니메이션과 인터랙티브 차트로 보는 영화와 극장 경험."><title>관람평을 읽으면, 경험이 보인다 | Cinema Intelligence</title><link rel="stylesheet" href="style.css"></head><body><a class="skip" href="#stage">본문으로 이동</a><header class="app-header"><a class="wordmark" href="#1"><span class="red-dot"></span>CINEMA <b>INTELLIGENCE</b></a><div class="header-actions"><button id="overviewBtn" aria-label="슬라이드 목차">목차 <kbd>G</kbd></button><button id="notesBtn" aria-label="발표자 노트">노트 <kbd>N</kbd></button><button id="fullBtn" aria-label="전체 화면">전체 화면 <kbd>F</kbd></button></div></header><main id="viewport"><div id="stage" tabindex="-1">{sections}</div></main><nav class="deck-nav" aria-label="슬라이드 이동"><div class="slide-status"><span id="position">01</span><span class="divider">/</span><span>{len(slides):02}</span><span id="currentTitle"></span></div><div class="nav-actions"><button id="autoBtn" aria-label="자동 재생">자동 재생</button><button id="prev" aria-label="이전 슬라이드">←</button><button id="next" aria-label="다음 슬라이드">→</button></div><div class="progress"><span id="progress"></span></div></nav><div id="overview" class="overlay" hidden><div class="overlay-top"><h2>슬라이드 목차</h2><button id="closeOverview">닫기 ×</button></div><div id="overviewGrid"></div></div><aside id="notes" hidden><h3>발표자 노트</h3><p id="noteText"></p><button id="closeNotes">닫기</button></aside><div id="tooltip" role="tooltip" hidden></div><div class="keyboard-help">← → 이동 · G 목차 · N 노트 · F 전체 화면 · Space 다음</div><script id="analysis" type="application/json">{json.dumps(summary,ensure_ascii=False).replace('<',chr(92)+'u003c')}</script><script src="deck.js"></script></body></html>'''
(out/'index.html').write_text(page,encoding='utf-8');(out/'.nojekyll').write_text('',encoding='utf-8')
(out/'.gitignore').write_text('.env\n.env.*\nnode_modules/\nqa/\n*.log\n',encoding='utf-8')
(out/'README.md').write_text('# Cinema Intelligence\n\n롯데시네마 예매순 TOP 10 영화의 공개 관람평 541개 분석을 담은 18장 HTML 슬라이드 덱.\n\n정적 HTML/CSS/JavaScript, 외부 라이브러리 없이 동작합니다. index.html을 브라우저에서 열거나 GitHub Pages로 배포할 수 있습니다.\n\n- 방향키·Space: 이동, G: 목차, N: 발표자 노트, F: 전체 화면\n- 주제 히트맵: 리뷰 수/비중 전환, 그래프: 툴팁\n- 인쇄: 슬라이드별 PDF 저장 가능\n- prefers-reduced-motion 지원\n\n분석은 최신순 편의 표본 및 표현 사전 매칭입니다. 평점·전체 관객 만족도를 추정하지 않습니다. 출처와 한계는 덱에 명시했습니다. 저장소에는 집계 데이터와 수집 원본·분석 보고서를 함께 보관합니다. .env와 실제 인증 정보는 제외합니다. 이미지 에셋은 GPT 이미지 생성 도구로 만든 콘셉트이며 실제 영화 장면·공식 시설 사진이 아닙니다. 생성 프롬프트는 assets/prompts.md를 참고하세요.\n',encoding='utf-8')
print('Created',len(slides),'slides at',out)
