'use strict';
const D=JSON.parse(document.getElementById('analysis').textContent),M=D.movies;
const COLORS=['#80b6a4','#ec514d','#d6b17a','#514c53'],SENT=['긍정 단서','부정 단서','혼합 단서','단서 없음'];
const names=['극장판 치이카와','암살자(들)','부활남: 더 레드','타짜: 벨제붑의 노래','오디세이','인턴','가능한 사랑','엔하이픈 VR 콘서트','옵세션','어벤져스: 엔드게임 앙코르'];
const E=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n).toLocaleString('ko-KR'),pct=(n,total)=>(n/total*100).toFixed(1)+'%';
const text=(x,y,t,size=17,fill='#c4adb7',anchor='start',extra='')=>`<text x="${x}" y="${y}" font-size="${size}" fill="${fill}" text-anchor="${anchor}" ${extra}>${E(t)}</text>`;
const rect=(x,y,w,h,fill,cls='',tip='')=>`<rect x="${x}" y="${y}" width="${Math.max(0,w)}" height="${h}" rx="3" fill="${fill}" class="${cls}" ${tip?`data-tip="${E(tip)}" tabindex="0" role="img" aria-label="${E(tip)}"`:''}/>`;
const line=(x,y,x2,y2,color='#352830')=>`<line x1="${x}" y1="${y}" x2="${x2}" y2="${y2}" stroke="${color}"/>`;
function mount(id,w,h,body,label){document.getElementById(id).innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${E(label)}"><title>${E(label)}</title>${body}</svg>`}
function cohort(){let b='';const max=Math.max(...M.map(m=>m.total_reviews));M.forEach((m,i)=>{const y=15+i*43;b+=text(0,y+18,String(m.rank).padStart(2,'0'),15,'#ec514d');b+=text(42,y+18,names[i],19,'#d8c7cf');b+=rect(405,y,850,25,'#251c23');b+=rect(405,y,850*m.total_reviews/max,25,i===4?'#ec514d':'#734349','grow',`${m.movie}\n전체 관람평 표시: ${fmt(m.total_reviews)}개\n수집: ${m.sample_reviews}개`);b+=text(1304,y+19,fmt(m.total_reviews),20,'#f1dddf','end');b+=text(1380,y+19,'n='+m.sample_reviews,13,'#99828f','end')});mount('cohort',1412,445,b,'예매순 상위 10편의 전체 관람평 표시 수')}
function coverage(){let b='';const x=410,w=790;[0,25,50,75,100].forEach(v=>{b+=line(x+w*v/100,12,x+w*v/100,430);b+=text(x+w*v/100,453,v+'%',13,'#8a7582','middle')});M.forEach((m,i)=>{const y=27+i*41;b+=text(0,y+5,names[i],18,'#d8c7cf');b+=rect(x,y-5,w*m.coverage_pct/100,10,i===7?'#d6b17a':'#ec514d','grow',`${m.movie}\n수집 ${m.sample_reviews} / 전체 표시 ${fmt(m.total_reviews)}\n수집 비중 ${m.coverage_pct}%`);b+=`<circle cx="${x+w*m.coverage_pct/100}" cy="${y}" r="6" fill="${i===7?'#d6b17a':'#ec514d'}" class="dot"/>`;b+=text(1260,y+6,m.coverage_pct.toFixed(2)+'%',18,'#f1dddf','end');b+=text(1388,y+6,`${m.sample_reviews} / ${fmt(m.total_reviews)}`,15,'#9e8794','end')});mount('coverage',1412,475,b,'영화별 수집 비중. VR 콘서트는 16개 중 16개')}
function sentiment(){const total=D.sample_total,cx=250,cy=205,r=137,c=2*Math.PI*r;let off=0,b='';b+=`<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="#251c23" stroke-width="38"/>`;SENT.forEach((s,i)=>{const n=D.sentiment[s],len=c*n/total;b+=`<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="${COLORS[i]}" stroke-width="38" stroke-dasharray="${Math.max(0,len-4)} ${c}" stroke-dashoffset="${-off}" transform="rotate(-90 ${cx} ${cy})" data-tip="${E(`${s}: ${n}개 (${pct(n,total)})`)}" class="dot"/>`;off+=len});b+=text(cx,cy+4,'541',69,'#f2e5e8','middle');b+=text(cx,cy+37,'수집 리뷰',17,'#9d8592','middle');SENT.forEach((s,i)=>{const y=420+Math.floor(i/2)*34,x=15+(i%2)*310;b+=rect(x,y-13,10,10,COLORS[i]);b+=text(x+21,y,s,15,'#c4adb7');b+=text(x+270,y,`${D.sentiment[s]} · ${pct(D.sentiment[s],total)}`,15,COLORS[i],'end')});mount('sentiment',630,490,b,'전체 541개 리뷰의 감성 표현 단서 분포')}
function sentimentMovies(){let b='';SENT.forEach((s,i)=>{b+=rect(405+i*230,3,13,13,COLORS[i]);b+=text(425+i*230,15,s,14,'#bca4b0')});M.forEach((m,i)=>{const y=42+i*39;b+=text(0,y+20,names[i],18,'#d8c7cf');let x=405;SENT.forEach((s,j)=>{const n=m.sentiment_counts[s]||0,w=870*n/m.sample_reviews;b+=rect(x,y,w,25,COLORS[j],'grow',`${m.movie}\n${s}: ${n} / ${m.sample_reviews}개 (${pct(n,m.sample_reviews)})`);if(w>46)b+=text(x+w/2,y+18,String(n),14,j===3?'#ddd0d7':'#171218','middle');x+=w});b+=text(1380,y+20,'n='+m.sample_reviews,14,'#ac92a2','end')});b+=text(405,455,'0%',13,'#8a7582');b+=text(1275,455,'100%',13,'#8a7582','end');mount('sentimentMovies',1412,475,b,'영화별 긍정 부정 혼합 미분류 표현 비중')}
function topics(){const topics=Object.keys(M[0].theme_counts).map(k=>({key:k,n:M.reduce((s,m)=>s+m.theme_counts[k],0)})).sort((a,b)=>b.n-a.n);let b='';const max=topics[0].n;topics.forEach((t,i)=>{const y=14+i*41;b+=text(0,y+20,t.key,20,'#d8c7cf');b+=rect(300,y,900,25,'#251c23');b+=rect(300,y,900*t.n/max,25,i<2?'#ec514d':'#75434d','grow',`${t.key}\n매칭 ${t.n} / ${D.sample_total}개 (${pct(t.n,D.sample_total)})\n다른 주제와 중복 가능`);b+=text(1270,y+20,String(t.n),21,'#f1dddf','end');b+=text(1390,y+20,pct(t.n,D.sample_total),15,'#a68b9b','end')});mount('topics',1412,440,b,'주제별 키워드가 매칭된 리뷰 수')}
let heatMode='rate';
function heatmap(){const keys=Object.keys(M[0].theme_counts),labels=['연기·배우','서사·연출','몰입·속도','영상·기기','원작 비교','역사·사회','공포·강도','굿즈·특전','서비스','재관람'];let b='',x0=365,cw=103,ch=37;labels.forEach((s,j)=>b+=text(x0+j*cw+cw/2,22,s,13,'#b498aa','middle'));M.forEach((m,i)=>{const y=38+i*ch;b+=text(0,y+24,names[i],17,'#cbb4c1');keys.forEach((k,j)=>{const n=m.theme_counts[k],v=n/m.sample_reviews,alpha=n?Math.min(.9,.12+v*1.8):.06,fill=`rgba(236,81,77,${alpha})`;b+=rect(x0+j*cw,y,cw-7,ch-5,fill,'cell',`${m.movie}\n${k}: ${n} / ${m.sample_reviews}개\n표본 내 비중 ${pct(n,m.sample_reviews)}\n복수 주제 매칭 가능`);b+=text(x0+j*cw+(cw-7)/2,y+22,heatMode==='rate'?pct(n,m.sample_reviews):String(n),13,n?'#f4e4e9':'#705562','middle')})});mount('heatmap',1412,426,b,'영화별 주제 키워드 매칭 히트맵')}
function scatter(){const w=835,h=420,x0=58,y0=30,pw=720,ph=320;let b='';for(let v=0;v<=40;v+=10){const x=x0+pw*v/40,y=y0+ph-ph*v/40;b+=line(x,y0,x,y0+ph);b+=line(x0,y,x0+pw,y);b+=text(x,y0+ph+26,v+'%',13,'#8e7384','middle');b+=text(x0-12,y+4,v+'%',13,'#8e7384','end')}const offsets=[[-8,-15],[-10,30],[12,5],[15,-10],[-10,-15],[10,-12],[12,-12],[12,4],[12,19],[12,-12]];M.forEach((m,i)=>{const a=m.theme_counts['연기·배우']/m.sample_reviews*100,c=m.theme_counts['서사·연출']/m.sample_reviews*100,x=x0+pw*a/40,y=y0+ph-ph*c/40,r=6+Math.sqrt(m.sample_reviews)*.5;const tip=`${m.movie}\n연기·배우 ${m.theme_counts['연기·배우']} / ${m.sample_reviews} (${a.toFixed(1)}%)\n서사·연출 ${m.theme_counts['서사·연출']} / ${m.sample_reviews} (${c.toFixed(1)}%)`;b+=`<circle cx="${x}" cy="${y}" r="${r}" fill="${i===6?'#d6b17a':'#ec514d'}" opacity=".8" class="dot" data-tip="${E(tip)}"/>`;const short=['치이카와','암살자','부활남','타짜','오디세이','인턴','가능한 사랑','VR','옵세션','어벤져스'][i];b+=text(x+offsets[i][0],y+offsets[i][1],short,12,'#d5bdca')});b+=text(x0+pw/2,h-7,'연기·배우 매칭 비중 →',14,'#a8899e','middle');b+=text(x0,16,'서사·연출 매칭 비중 ↑',13,'#a8899e');mount('scatter',w,h,b,'연기 배우와 서사 연출 주제 매칭 비중 비교')}
function horizontal(id,rows,total,label,width=640,height=350){let b='';rows.forEach((r,i)=>{const y=27+i*92;b+=text(0,y,r.label,20,'#d9c3ce');b+=rect(0,y+17,width-80,23,'#251b23');b+=rect(0,y+17,(width-80)*r.n/total,23,r.color||'#ec514d','grow',`${r.label}\n${r.n} / ${total}개 (${pct(r.n,total)})`);b+=text(width-5,y+36,String(r.n)+'개',20,'#ecdbe5','end')});mount(id,width,height,b,label)}
function rewatch(){let b='';const keys=['영상·음향·기기','재관람·추천 의향'];keys.forEach((k,i)=>{b+=rect(370+i*300,2,14,14,i?'#d6b17a':'#ec514d');b+=text(394+i*300,16,k,16,'#bfa4b3')});[4,9].forEach((idx,i)=>{const m=M[idx],y=80+i*120;b+=text(0,y+40,names[idx],22,'#d9c1cf');keys.forEach((k,j)=>{const v=m.theme_counts[k],by=y+j*39;b+=rect(370,by,850,24,'#251b23');b+=rect(370,by,850*v/12,24,j?'#d6b17a':'#ec514d','grow',`${m.movie}\n${k}: ${v} / 60개 (${pct(v,60)})`);b+=text(1290,by+19,v+'개',21,'#e7d1e1','end')})});[0,4,8,12].forEach(v=>b+=text(370+850*v/12,344,v+'개',13,'#8d7285','middle'));mount('rewatch',1412,365,b,'오디세이와 어벤져스의 영상 음향 및 재관람 주제 비교')}
cohort();coverage();sentiment();sentimentMovies();topics();heatmap();scatter();horizontal('revival',[{label:'연기·배우',n:17},{label:'서사·연출',n:11,color:'#d6b17a'},{label:'영상·음향·기기',n:11,color:'#8b546a'}],60,'부활남 주요 주제 매칭 수',660,330);horizontal('vr',[{label:'영상·음향·기기',n:5},{label:'극장 서비스·매너',n:3,color:'#d6b17a'},{label:'원작·시리즈 비교',n:3,color:'#8b546a'}],16,'VR 콘서트 주요 주제 매칭 수',700,310);rewatch();
const slides=[...document.querySelectorAll('.slide')];let current=0,auto=null;
const $=id=>document.getElementById(id),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function fit(){if(innerWidth<=700){$('stage').style.transform='';return}const v=$('viewport'),scale=Math.min(v.clientWidth/1600,v.clientHeight/900);$('stage').style.transform=`scale(${scale})`}
function counters(s){s.querySelectorAll('[data-count]').forEach(el=>{const end=Number(el.dataset.count),t0=performance.now();function step(t){if(!s.classList.contains('active'))return;const f=reduced?1:Math.min(1,(t-t0)/1100);el.textContent=fmt(Math.round(end*(1-Math.pow(1-f,3))));if(f<1)requestAnimationFrame(step)}requestAnimationFrame(step)})}
function go(i,hash=true){current=Math.max(0,Math.min(slides.length-1,i));slides.forEach((s,j)=>{s.classList.toggle('active',j===current);s.classList.remove('drawn');s.setAttribute('aria-hidden',String(j!==current));s.inert=j!==current});const s=slides[current];$('position').textContent=String(current+1).padStart(2,'0');$('currentTitle').textContent=s.dataset.title;$('noteText').textContent=s.dataset.notes;$('prev').disabled=current===0;$('next').disabled=current===slides.length-1;$('progress').style.width=((current+1)/slides.length*100)+'%';if(hash)history.replaceState(null,'','#'+(current+1));if(innerWidth<=700)scrollTo({top:0,behavior:'instant'});counters(s);requestAnimationFrame(()=>requestAnimationFrame(()=>s.classList.add('drawn')));document.title=`${current+1}/${slides.length} · ${s.dataset.title} | Cinema Intelligence`;if(current===slides.length-1&&auto)toggleAuto();$('tooltip').hidden=true}
function overview(open){$('overview').hidden=!open;if(open){$('overviewGrid').innerHTML=slides.map((s,i)=>`<button data-slide="${i}" class="${i===current?'current':''}"><strong>${String(i+1).padStart(2,'0')}</strong><span>${E(s.dataset.title)}</span></button>`).join('');$('overviewGrid').querySelectorAll('button').forEach(b=>b.onclick=()=>{go(Number(b.dataset.slide));overview(false)});$('closeOverview').focus()}else $('overviewBtn').focus()}
function toggleNotes(){const open=$('notes').hidden;$('notes').hidden=!open;if(open)$('closeNotes').focus()}
function toggleAuto(){if(auto){clearInterval(auto);auto=null;$('autoBtn').textContent='자동 재생';$('autoBtn').classList.remove('active')}else{auto=setInterval(()=>go(current+1),14000);$('autoBtn').textContent='재생 중 · 정지';$('autoBtn').classList.add('active')}}
async function full(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{const help=document.querySelector('.keyboard-help');help.textContent='브라우저의 F11 키로 전체 화면을 사용할 수 있습니다';help.classList.add('show')}}
$('prev').onclick=()=>go(current-1);$('next').onclick=()=>go(current+1);$('autoBtn').onclick=toggleAuto;$('overviewBtn').onclick=()=>overview(true);$('closeOverview').onclick=()=>overview(false);$('notesBtn').onclick=toggleNotes;$('closeNotes').onclick=()=>{$('notes').hidden=true;$('notesBtn').focus()};$('fullBtn').onclick=full;
document.querySelectorAll('[data-heat]').forEach(b=>b.onclick=()=>{heatMode=b.dataset.heat;document.querySelectorAll('[data-heat]').forEach(x=>x.classList.toggle('active',x===b));heatmap()});
addEventListener('resize',fit);addEventListener('hashchange',()=>{const n=Number(location.hash.slice(1));if(Number.isFinite(n)&&n>=1&&n<=slides.length)go(n-1,false)});
addEventListener('keydown',ev=>{if(ev.target.closest('input,textarea,select'))return;if(ev.key==='Escape'){$('overview').hidden=true;$('notes').hidden=true;return}if(!$('overview').hidden)return;if(ev.target.closest('button,a')&&['Enter',' '].includes(ev.key))return;const key=ev.key.toLowerCase();if(['ArrowRight','ArrowDown','PageDown',' '].includes(ev.key)){ev.preventDefault();go(current+1)}else if(['ArrowLeft','ArrowUp','PageUp'].includes(ev.key)){ev.preventDefault();go(current-1)}else if(key==='g')overview(true);else if(key==='n')toggleNotes();else if(key==='f')full();else if(key==='home')go(0);else if(key==='end')go(slides.length-1)});
let touchX=0,touchY=0;$('viewport').addEventListener('touchstart',ev=>{touchX=ev.changedTouches[0].clientX;touchY=ev.changedTouches[0].clientY},{passive:true});$('viewport').addEventListener('touchend',ev=>{const dx=ev.changedTouches[0].clientX-touchX,dy=ev.changedTouches[0].clientY-touchY;if(Math.abs(dx)>80&&Math.abs(dx)>Math.abs(dy)*1.6)go(current+(dx<0?1:-1))},{passive:true});
function tip(ev){const target=ev.target.closest('[data-tip]');if(!target){$('tooltip').hidden=true;return}const box=$('tooltip');box.textContent=target.dataset.tip;box.hidden=false;const r=target.getBoundingClientRect(),x=ev.clientX??r.x,y=ev.clientY??r.y;box.style.left=Math.max(8,Math.min(innerWidth-box.offsetWidth-12,x+16))+'px';box.style.top=Math.max(8,Math.min(innerHeight-box.offsetHeight-12,y+16))+'px'}
document.addEventListener('pointermove',tip);document.addEventListener('focusin',tip);document.addEventListener('focusout',()=>{$('tooltip').hidden=true});
const initial=Number(location.hash.slice(1));go(Number.isFinite(initial)&&initial>=1&&initial<=slides.length?initial-1:0,false);fit();const help=document.querySelector('.keyboard-help');setTimeout(()=>help.classList.add('show'),1000);setTimeout(()=>help.classList.remove('show'),6500);
